### ISSUE TITLE
admin user can not see the videos of other users?

### ISSUE THREAD

**Issue by zen85** [elonen/clapshot#57]
when i log in with the default admin user i have the same view as a normal user. i was under the impression that the "admin" can edit the videos of all the users? or am i wrong about that?

**Comment by elonen** [comment]
Technically you're correct, admin has the power to delete and rename anyone's videos, but there's currently no UI to list anyone else's videos except your own. Because of that, in the current release, admin user is mostly useful as a comment moderator, since it can edit and delete anyone's comments (while regular users can only modify their own).

The `dev` branch adds support for folders, both virtual, user-created and plugin-defined, which allows adding admin a clean UI to see everyone's videos in a structured, non-cluttered manner. Before releasing the dev branch though, I want to rework how the "organizer" plugins access database first, as changing it after other people start writing their own plugins would make drastic changes very  painful for everyone.

If you have some perssing, specific scenario you're facing, I'd like to hear about it though. Adding some kind of a workaround for this before the dev merge is not out of the question if there's need for it.

**Comment by zen85** [comment]
oh i see! thank you! i cant stress enough how important people like you are for the selfhosted community!

i actually need to get away from frame.io for legal reasons concerning a specific client. i can use clapshot for that already and i love you for that. but right now i have to make a specific user for that specific client. the first problem is that clients are seemingly unable to put in a user and a password... so an anonymous link share would already be cool - but that is a different topic.

but now this specific client is not my sole client. as an admin i want to be able to manage all my clients. because right now i would have to login with the same credentials my client uses to upload a new version (oh yeah... versioning is another nice to have topic...)

If i would have a true admin user with true admin capabilities where i can manage all my clients that would be very amazing!

**Comment by elonen** [comment]
The `basic_folders` Organizer plugin (a.k.a. folder UI for Clapshot) now shows admin(s) a view of all active users' folders. When uploading or moving existing videos in them, ownership of those videos is transferred to the user whose folder they are moved in.

I'll make a new release during the weekend, which includes this feature.

**Comment by zen85** [comment]
wow. this sounds perfect! i will try that immidiatly. i currenty have clapshot running on my dedicated rpi since i had problems with running it in a docker container utilising your install script. but its worth its own machine!

**Comment by elonen** [comment]
The 0.6.0 release is out now.
